E0s: '{13:-0.01623775, 8:-0.02536379}'
amsgrad: true
batch_size: 1
checkpoints_dir: .\MACE_models\checkpoints
correlation: 3
default_dtype: float64
device: cuda
ema: true
ema_decay: 0.99
energy_key: REF_energy
error_table: PerAtomRMSE
forces_key: REF_forces
log_dir: .\MACE_models\logs
max_L: 1
max_num_epochs: 150
model: MACE
model_dir: .\MACE_models
num_channels: 128
num_interactions: 2
r_max: 7.0
restart_latest: true
results_dir: .\MACE_models\results
save_cpu: true
seed: 123
swa: true
test_file: C:\Users\Galib\Downloads\AtomProNet-main(1)\AtomProNet-main\example_dataset\hydrostatic_strain\test.extxyz
train_file: C:\Users\Galib\Downloads\AtomProNet-main(1)\AtomProNet-main\example_dataset\hydrostatic_strain\train.extxyz
valid_batch_size: 1
valid_file: C:\Users\Galib\Downloads\AtomProNet-main(1)\AtomProNet-main\example_dataset\hydrostatic_strain\validation.extxyz
